-- MySQL Script generated by MySQL Workbench
-- Wed 18 Nov 2015 17:44:14 BRST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema multas_rodovias_federais
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema multas_rodovias_federais
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `multas_rodovias_federais` DEFAULT CHARACTER SET utf8 ;
USE `multas_rodovias_federais` ;

-- -----------------------------------------------------
-- Table `multas_rodovias_federais`.`tbl_gravidade_infracao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `multas_rodovias_federais`.`tbl_gravidade_infracao` (
  `cod_gravidade` INT NOT NULL,
  `num_pontos` INT NOT NULL,
  `desc_gravidade` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`cod_gravidade`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `multas_rodovias_federais`.`tbl_infracao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `multas_rodovias_federais`.`tbl_infracao` (
  `cod_infracao` INT NOT NULL,
  `desc_infracao` VARCHAR(350) NOT NULL,
  `cod_gravidade` INT NOT NULL,
  `valor` REAL NOT NULL,
  PRIMARY KEY (`cod_infracao`),
  INDEX `fk_tbl_infracao_tbl_gravidade_infracao1_idx` (`cod_gravidade` ASC),
  CONSTRAINT `fk_tbl_infracao_tbl_gravidade_infracao1`
    FOREIGN KEY (`cod_gravidade`)
    REFERENCES `multas_rodovias_federais`.`tbl_gravidade_infracao` (`cod_gravidade`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `multas_rodovias_federais`.`tbl_condutor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `multas_rodovias_federais`.`tbl_condutor` (
  `cod_condutor` INT NOT NULL,
  `primeiro_nome` VARCHAR(45) NOT NULL,
  `ultimo_nome` VARCHAR(45) NOT NULL,
  `tipo_cnh` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`cod_condutor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `multas_rodovias_federais`.`tbl_multa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `multas_rodovias_federais`.`tbl_multa` (
  `cod_auto` VARCHAR(11) NOT NULL,
  `cod_infracao` INT NOT NULL,
  `cod_condutor` INT NOT NULL,
  `data_infracao` DATE NOT NULL,
  PRIMARY KEY (`cod_auto`),
  INDEX `fk_tbl_multa_tbl_infracao1_idx` (`cod_infracao` ASC),
  INDEX `fk_tbl_multa_tbl_condutor1_idx` (`cod_condutor` ASC),
  CONSTRAINT `fk_tbl_multa_tbl_infracao1`
    FOREIGN KEY (`cod_infracao`)
    REFERENCES `multas_rodovias_federais`.`tbl_infracao` (`cod_infracao`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_tbl_multa_tbl_condutor1`
    FOREIGN KEY (`cod_condutor`)
    REFERENCES `multas_rodovias_federais`.`tbl_condutor` (`cod_condutor`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `multas_rodovias_federais`.`tbl_telefones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `multas_rodovias_federais`.`tbl_telefones` (
  `cod_telefone` INT NOT NULL AUTO_INCREMENT,
  `num_telefone` VARCHAR(15) NULL,
  `cod_local` VARCHAR(3) NULL,
  PRIMARY KEY (`cod_telefone`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `multas_rodovias_federais`.`tbl_condutor_tem_telefones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `multas_rodovias_federais`.`tbl_condutor_tem_telefones` (
  `cod_condutor` INT NOT NULL,
  `cod_telefone` INT NOT NULL,
  `tipo_telefone` VARCHAR(15) NULL,
  PRIMARY KEY (`cod_condutor`, `cod_telefone`),
  INDEX `fk_tbl_condutor_has_tbl_telefones_tbl_telefones1_idx` (`cod_telefone` ASC),
  INDEX `fk_tbl_condutor_has_tbl_telefones_tbl_condutor1_idx` (`cod_condutor` ASC),
  CONSTRAINT `fk_tbl_condutor_has_tbl_telefones_tbl_condutor1`
    FOREIGN KEY (`cod_condutor`)
    REFERENCES `multas_rodovias_federais`.`tbl_condutor` (`cod_condutor`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_tbl_condutor_has_tbl_telefones_tbl_telefones1`
    FOREIGN KEY (`cod_telefone`)
    REFERENCES `multas_rodovias_federais`.`tbl_telefones` (`cod_telefone`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
